pipeline {
    agent any
    
    stages {
        stage('Pull Repo') {
            steps {
                git branch: 'jenkinsfile', url: 'https://github.com/Dan-Mihaylov/DevOps'
            }
        }
        
        stage('Install Node.js Manually') {
            steps {
                sh '''
                curl -sL https://deb.nodesource.com/setup_14.x | bash -
                apt-get install -y nodejs
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'cd Student-Registry-App'
                sh 'ls'
            }
        }

        stage('Test Application') {
            steps {
                sh 'cd Student-Registry-App'
                sh 'ls'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up workspace...'
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
