name: Selenium Web Driver

on:
  push:
    branches:
      - selenium-web-driver
  pull_request:
    branches:
      - selenium-web-driver
  workflow_dispatch:

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version:
          6.0.x

    - name: Install Dependencies
      run: dotnet restore SeleniumBasicExercise.sln
      working-directory: ./Selenium-Web-Driver

    - name: Build Application
      run: dotnet build SeleniumBasicExercise.sln --no-restore
      working-directory: ./Selenium-Web-Driver
    
    - name: Test Project 1
      # env:
      #   CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: |
        echo "Running Tests For Project 1"
        dotnet test TestProject1/TestProject1.csproj --verbosity normal
      working-directory: ./Selenium-Web-Driver
    
    - name: Test Project 2
      # env:
      #   CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: |
        echo "Running Tests For Projct 2"
        dotnet test TestProject2/TestProject2.csproj --verbosity normal
      working-directory: ./Selenium-Web-Driver
    
    - name: Test Project 3
      # env:
      #   CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: |
        echo "Running Tests For Project 3"
        dotnet test TestProject3/TestProject3.csproj --verbosity normal
