name: Student Registry App

on:
  push:
    branches: [ "student-registry-app" ]
  pull_request:
    branches: [ "student-registry-app" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # Implement running on three different machines later on
    # strategy:
    #   matrix:
    #     node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Install
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
