name: Student Registry App

on:
  push:
    branches:
      - student-registry-app
  pull_request:
    branches:
      - student-registry-app
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    # Implement running on three different machines later on
    # strategy:
    #   matrix:
    #     node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Install Node
      uses: actions/setup-node@v4
    
    - name: Install Dependencies
      run: npm install
      working-directory: ./Student-Registry-App
    
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
        
    - name: Install Node
      uses: actions/setup-node@v4
      
    - name: Install Dependencies
      run: npm install
      working-directory: ./Student-Registry-App

    - name: Testing Application
      run: npm run test
      working-directory: ./Student-Registry-App
    
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    
    - name: Deploy to Render
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
        api_key: ${{ secrets.MY_RENDER_API_KEY }}
        wait_deploy: true 
